server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Gateway-Request, true
          discovery:
            locator:
              enabled: true
          routes:
            - id: ordenes
              uri: lb://MS-ORDENES
              predicates:
                - Path=/orden/**
              filters:
                - RewritePath=/orden/(?<segment>.*), /api/orden/${segment}
            - id: requerimiento
              uri: lb://MS-REQUERIMIENTO
              predicates:
                - Path=/requerimiento/**
              filters:
                - RewritePath=/requerimiento/(?<segment>.*), /api/requerimiento/${segment}
            - id: recepcion
              uri: lb://MS-RECEPCION
              predicates:
                - Path=/recepcion/**
              filters:
                - RewritePath=/recepcion/(?<segment>.*), /api/pedidos-pendientes/${segment}
            - id: pedidodependencia
              uri: lb://MS-PEDIDODEPENDENCIA
              predicates:
                - Path=/pedidodependencia/**
              filters:
                - RewritePath=/pedidodependencia/(?<segment>.*), /api/pedidodependencia/${segment}
            - id: login
              uri: lb://MS-LOGIN
              predicates:
                - Path=/login/**
              filters:
                - RewritePath=/login/(?<segment>.*), /api/login/${segment}
            - id: roles
              uri: lb://MS-LOGIN
              predicates:
                - Path=/roles/**
              filters:
                - RewritePath=/roles/(?<segment>.*), /api/roles/${segment}
            - id: usuarios
              uri: lb://MS-LOGIN
              predicates:
                - Path=/usuarios/**
              filters:
                - RewritePath=/usuarios/(?<segment>.*), /api/usuarios/${segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
