server:
  port: 8082

spring:
  application:
    name: ms-ordenes
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ORDENES_DB_URL}
    username: ${ORDENES_DB_USERNAME}
    password: ${ORDENES_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2  
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      

springdoc:
  swagger-ui:
    path: /docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
