server:
  port: 8082

spring:
  application:
    name: ms-ordenes
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:8888}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-ordenes:3306/ordenesDb
    username: root
    password: root
    hikari:
      maximum-pool-size: 2  
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
