spring.application.name=ms-pedidodependencia
server.port=8084

# --- CockroachDB (protocolo compatible con PostgreSQL) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://cockroachdb:26257/sudab_pedido_dependencia?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.CockroachDialect
spring.jpa.show-sql=false
spring.flyway.enabled=true

eureka.client.service-url.defaultZone=${EUREKA_URI:http://eureka-server:8761/eureka}
eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
