apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 config-server 8888; do
                echo "Esperando a config-server..."
                sleep 2
              done
      containers:
        - name: eureka-server
          image: eureka-server
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 15
      restartPolicy: Always
