apiVersion: v1
kind: Service
metadata:
  name: ms-requerimiento
  labels:
    app: ms-requerimiento
spec:
  type: ClusterIP
  selector:
    app: ms-requerimiento
  ports:
    - name: http
      port: 8080
      targetPort: 8083
