apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pedidodependencia-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db-pedidodependencia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pedidodependencia-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
