server:
  port: 8087

spring:
  application:
    name: ms-kardex
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/