apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-login-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db-login
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-login-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
