apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-login-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-login:5432/logindb"
  SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "false"
