apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: config-server
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - wget --no-verbose --tries=1 --spider http://localhost:8888/ms-recepcion/default || exit 1
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
