apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ms-pedidodependencia
  name: ms-pedidodependencia
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    io.kompose.service: ms-pedidodependencia
