apiVersion: v1
kind: Service
metadata:
  name: db-ordenes
  labels:
    app: db-ordenes
spec:
  type: ClusterIP
  selector:
    app: db-ordenes
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
