apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-ordenes-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db-ordenes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-ordenes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
