apiVersion: v1
kind: Secret
metadata:
  name: db-ordenes-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ordenes_root_local"
  MYSQL_DATABASE: "ordenesdb"
  MYSQL_USER: "ordenes_user"
  MYSQL_PASSWORD: "ordenes_pass_local"
