spring:
  application:
    name: ms-requerimiento
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://jazzed-llama-18391.jxf.gcp-us-west2.cockroachlabs.cloud:26257/PROFORMAS?sslmode=verify-full}
    username: ${SPRING_DATASOURCE_USERNAME:mitchell}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
