server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway-Request, true
      routes:
        - id: login
          uri: http://ms-login:8086
          predicates:
            - Path=/login/**
          filters:
            - RewritePath=/login/(?<segment>.*), /api/login/${segment}
        - id: login-base
          uri: http://ms-login:8086
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /api/login
        - id: roles
          uri: http://ms-login:8086
          predicates:
            - Path=/roles/**
          filters:
            - RewritePath=/roles/(?<segment>.*), /api/roles/${segment}
        - id: roles-base
          uri: http://ms-login:8086
          predicates:
            - Path=/roles
          filters:
            - RewritePath=/roles, /api/roles
        - id: usuarios
          uri: http://ms-login:8086
          predicates:
            - Path=/usuarios/**
          filters:
            - RewritePath=/usuarios/(?<segment>.*), /api/usuarios/${segment}
        - id: usuarios-base
          uri: http://ms-login:8086
          predicates:
            - Path=/usuarios
          filters:
            - RewritePath=/usuarios, /api/usuarios
        - id: ordenes
          uri: http://ms-ordenes:8082
          predicates:
            - Path=/orden/**
          filters:
            - RewritePath=/orden/(?<segment>.*), /api/ordenes/${segment}
        - id: requerimiento
          uri: http://ms-requerimiento:8083
          predicates:
            - Path=/requerimiento/**
          filters:
            - RewritePath=/requerimiento/(?<segment>.*), /api/requerimientos/${segment}
        - id: recepcion
          uri: http://ms-recepcion:8085
          predicates:
            - Path=/recepcion/**
          filters:
            - RewritePath=/recepcion/(?<segment>.*), /api/pedidos-pendientes/${segment}
        - id: pedidodependencia
          uri: http://ms-pedidodependencia:8084
          predicates:
            - Path=/pedidodependencia/**
          filters:
            - RewritePath=/pedidodependencia/(?<segment>.*), /api/dependencias/${segment}
        - id: kardex
          uri: http://ms-kardex:8087
          predicates:
            - Path=/kardex/**
          filters:
            - RewritePath=/kardex/(?<segment>.*), /api/kardex/${segment}
        - id: productos
          uri: http://ms-kardex:8087
          predicates:
            - Path=/productos/**
          filters:
            - RewritePath=/productos/(?<segment>.*), /api/productos/${segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,gateway.routes
