server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: login
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/login/**
          filters:
            - RewritePath=/login/(?<segment>.*), /api/login/${segment}
        - id: login-base
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /api/login
        - id: roles
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/roles/**
          filters:
            - RewritePath=/roles/(?<segment>.*), /api/roles/${segment}
        - id: roles-base
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/roles
          filters:
            - RewritePath=/roles, /api/roles
        - id: usuarios
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/usuarios/**
          filters:
            - RewritePath=/usuarios/(?<segment>.*), /api/usuarios/${segment}
        - id: usuarios-base
          uri: https://ms-login-9l2y.onrender.com
          predicates:
            - Path=/usuarios
          filters:
            - RewritePath=/usuarios, /api/usuarios

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
