server:
  port: 8082

spring:
  application:
    name: ms-ordenes
  config:
    import: configserver:https://config-serve.onrender.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ORDENES_DB_URL}
    username: ${ORDENES_DB_USERNAME}
    password: ${ORDENES_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      

springdoc:
  swagger-ui:
    path: /docs

eureka:
  client:
    service-url:
      defaultZone: https://sistema-abastecimiento-microservicios.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true