apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-ordenes-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:mysql://db-ordenes:3306/ordenesdb?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "false"
