apiVersion: v1
kind: Service
metadata:
  name: ms-ordenes
  labels:
    app: ms-ordenes
spec:
  type: ClusterIP
  selector:
    app: ms-ordenes
  ports:
    - name: http
      port: 8080
      targetPort: 8082
