apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-recepcion-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-recepcion:5432/recepciondb"
  SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "false"
