apiVersion: v1
kind: Secret
metadata:
  name: db-kardex-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "kardex_root_local"
  MYSQL_DATABASE: "kardexdb"
  MYSQL_USER: "kardex_user"
  MYSQL_PASSWORD: "kardex_pass_local"
